export type ConditionType = "back" | "shoulder" | "knee";
export type RiskBand = "Low" | "Moderate" | "High" | "Very High";
export type ClinicianCall = "green" | "amber" | "red";

export interface ClinicalRule {
  id: string;
  name: string;
  category: "Red Flag" | "Clinical" | "Demographic" | "Lifestyle" | "Psychosocial";
  description: string;
  weight: number;
  evaluate: (input: any) => boolean;
}

export interface FiredRule {
  rule: ClinicalRule;
  evidence: string;
}

export interface PredictionResult {
  id: string;
  createdAt: Date;
  region: ConditionType;
  score: number; // 0-100
  band: RiskBand;
  firedRules: FiredRule[];
  chronicityWeeks: number;
  predictedCall: ClinicianCall;
  clinicianCall?: ClinicianCall; // set later as ground truth for validation
}

export function evaluateRules(
  rules: ClinicalRule[],
  input: any
): { firedRules: FiredRule[]; rawScore: number } {
  const firedRules: FiredRule[] = [];
  let rawScore = 0;

  for (const rule of rules) {
    if (rule.evaluate(input)) {
      firedRules.push({
        rule,
        evidence: "", // evidence should be generated by the engine
      });
      rawScore += rule.weight;
    }
  }

  // Cap score at 100
  rawScore = Math.min(rawScore, 100);

  return { firedRules, rawScore };
}

export function scoreToRiskBand(score: number): RiskBand {
  if (score < 20) return "Low";
  if (score < 45) return "Moderate";
  if (score < 70) return "High";
  return "Very High";
}

export function riskBandToCall(band: RiskBand): ClinicianCall {
  switch (band) {
    case "Low":
      return "green";
    case "Moderate":
      return "amber";
    case "High":
    case "Very High":
      return "red";
  }
}

export function estimateChronicityWeeks(painDuration: string): number {
  if (painDuration.includes("Acute")) return 3;
  if (painDuration.includes("Subacute")) return 8;
  if (painDuration.includes("Chronic")) return 16;
  return 6; // default
}
